export const ApiURLs = {
  login: 'api/Auth/login',
  forgetPassword: 'api/Account/ResetPassword',
  resetPassword: '/api/Account/ChangePassword',
  register: '/api/Account/Register',
  contact: '/api/Email/Send',
  order: '/api/ShoppingOrder/add',
  updateOrder: '/api/ShoppingOrder/update',
  catergories: '/api/Store/Categories',
  myProfile: '/api/Account/MyProfile',
  myProfiles: '/api/Account/MyProfiles',
  createProfile: '/api/Account/CreateProfile',
  myProfileByKey: '/api/Account/ProfileByQrcode',
  QrCode: '/api/Media/QrProfilebyUser',
  OfflineQrCode: '/api/Media/offlinesharing',
  connections: '/api/UserConnection/MyConnections',
  groups: '/api/ConnectionGroup',
  links: '/api/CustomLink',
  discount: '/api/discount', // Updated to use our proxy endpoint
  lockStatus: '/api/Account/UpdateLockStatus',
  collectInfo: '/api/Account/UpdateAutoConnect',
  directLink: '/api/Account/UpdateDirectUrl',
  linkQrCode: '/api/Account/LinkQrCode',
  analytics: '/api/Account/Analytics',
  addConnection: '/api/UserConnection/Add',
  updateProfile: '/api/Account/UpdateProfile',
  updateBulkLinksSort: '/api/CustomLink/BulkUpdateSort',
  deleteConnection: '/api/UserConnection/Delete',
  exportContactsFile: '/api/UserConnection/ExportToExcelFile',
  addContactToGroup: '/api/UserConnection/UpdateGroup',
  uploadProfileImage: '/api/Media/UploadProfileImage',
  uploadCoverImage: '/api/Media/UploadCoverImage',
  updateSubscription: '/api/Account/Subscribe',
  visitCount: '/api/CustomLink/Visit',
  blogs: '/api/Blogs',
  updateUserVisits: '/api/Account/Visit',
  updateEmail: '/api/Account/UpdateEmail',
} as const;
